[package]
name = "workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
models = { path = "../models" }
tokio = { version = "1.33.0", features = ["full"] }
async-trait = "0.1.74"
tracing = { workspace = true }
regex = "1.10.2"
rand = "0.8.5"

[dev-dependencies]
mockall = "0.12.0"
test-log = { version = "0.2.13", default-features = false, features = [
  "trace",
] }
tracing-subscriber = { workspace = true }
