[package]
name = "workspace"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
tracing = { workspace = true }
rand = { workspace = true }
uuid = { workspace = true }
infrastructure = { path = "../infrastructure" }
octocrab = { workspace = true }
tokio = { workspace = true }
shell-escape = { workspace = true }
bollard = "0.16.1"
futures-util = "0.3.30"

[dev-dependencies]
test-log = { workspace = true }
tracing-subscriber = { workspace = true }
regex = { workspace = true }
